apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: simple-demo
spec:
  license:
    accept: true
    license: L-KPRV-AUG9NC 
    use: CloudPakForIntegrationNonProduction  
  configurations:
    - ace-simple-demo-policy
    - ace-simple-demo-sever-conf
    - bar-auth
    - qm-client.kdb
    - qm-client.rdb
    - qm-client.sth
  barURL:
    - https://github.com/thanosz/ace-projects-demo/raw/refs/heads/main/simple-demo.bar
  replicas: 1
  version: "13.0"
